auth_base_url: null
benchmark: false
benchmark_results: null
docai_password: null
docai_user: null
dry_run: false
images: null
keycloak_client_id: null
keycloak_realm: null
list_images: false
log_level: DEBUG
name: null
num_replicas: 8
num_requests: 8
out_dir: null
pipeline: null
platform_client_id: null
platform_token: null
scorer_base_url: null
scorer_logs: false
temp_image_dir: null
token_endpoint_url: null
valid_image_file_extensions:
- .pdf
- .jpeg
- .jpg
- .png
- .bmp
- .tiff
- .gif
verbose: false
version: 0.2.4
