name: Security

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  snyk-code-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v0.7
      - name: Install Snyk CLI
        run:  npm install -g snyk
      - name: Run Snyk Static Code test
        run:  snyk code test --severity-threshold=high